name: fnps
description: "Flutter NoPayStation client"
publish_to: 'none'
version: 1.1.1+0

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path: ^1.9.1
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  file_picker: ^10.3.8
  csv: ^6.0.0
  provider: ^6.1.5
  crypto: ^3.0.7
  xml: ^6.6.1
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_hooks: ^0.21.3
  flutter_html: 3.0.0
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  zustand: ^0.0.5
  hive_ce: ^2.16.0
  hive_ce_flutter: ^2.3.3
  dio: ^5.9.0
  android_x_storage: ^1.0.2
  permission_handler: ^12.0.1
  device_info_plus: ^12.3.0
  saf_util: ^0.11.0
  saf_stream: ^0.12.3
  collection: ^1.19.1
  open_dir: ^0.0.2
  open_file_manager: ^2.0.1
  dynamic_color: ^1.8.1
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  hive_ce_generator: ^1.10.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/